// BOOK_SEAT ==== CARD_ADD_ITEM
//  REMOVE_SEAT === CARD_REMOVE_ITEM
// BOOKSEATS_SHIPPING_ADDRES  === CART_SAVE_SHIPPING_ADDRESS
// SAVE_PAYMENT_METHOD === CART_SAVE_PAYMENT_METHOD
// BOOKSEATS_EMPTY === cart_empty
export const BOOK_SEAT = 'BOOK_SEAT';
export const REMOVE_SEAT = 'REMOVE_SEAT';
export  const BOOKSEATS_SHIPPING_ADDRES = 'BOOKSEATS_SHIPPING_ADDRES';
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';
export  const BOOKSEATS_EMPTY = 'BOOKSEATS_EMPTY';
