// PRODUCT
export const BUS_LIST_REQUEST = 'BUS_LIST_REQUEST';
export const BUS_LIST_SUCCESS = 'BUS_LIST_SUCCESS';
export const BUS_LIST_FAIL = 'BUS_LIST_FAIL'; 

export const BUS_DETAILS_REQUEST = 'BUS_DETAILS_REQUEST';
export const BUS_DETAILS_SUCCESS = 'BUS_DETAILS_SUCCESS';
export const BUS_DETAILS_FAIL = 'BUS_DETAILS_FAIL'; 

export const BUS_CREATE_REQUEST = 'BUS_CREATE_REQUEST'
export const BUS_CREATE_SUCCESS = 'BUS_CREATE_SUCCESS'
export const BUS_CREATE_FAIL = 'BUS_CREATE_FAIL'
export const BUS_CREATE_RESET = 'BUS_CREATE_RESET'

export const BUS_UPDATE_REQUEST = 'BUS_UPDATE_REQUEST'
export const BUS_UPDATE_SUCCESS = 'BUS_UPDATE_SUCCESS'
export const BUS_UPDATE_FAIL = 'BUS_UPDATE_FAIL'
export const BUS_UPDATE_RESET = 'BUS_UPDATE_RESET'



export const BUS_DELETE_REQUEST = 'BUS_DELETE_REQUEST'
export const BUS_DELETE_SUCCESS = 'BUS_DELETE_SUCCESS'
export const BUS_DELETE_FAIL = 'BUS_DELETE_FAIL'
export const BUS_DELETE_RESET = 'BUS_DELETE_RESET'

export const BUS_CATEGORY_LIST_REQUEST = 'BUS_CATEGORY_LIST_REQUEST'
export const BUS_CATEGORY_LIST_SUCCESS = 'BUS_CATEGORY_LIST_SUCCESS'
export const BUS_CATEGORY_LIST_FAIL = 'BUS_CATEGORY_LIST_FAIL'
